package com.qantasloyalty.lsl.etlservice.model

data class ApplicationAbove90Data(
        val applicationId: String?,
        val offerId: String?,
        val registrationNumber: String?,
        val use: String?,
        val accessories: Boolean,
        val factoryOptions: Boolean,
        val previouInsuranceCompanyName: String?,
        val previousInsuranceExpiryDate: String?,
        val purchaseDetailsPurchasePrice: Int?,
        val purchaseDetailsPurchaseDate: String?,
        val make: String?,
        val model: String?,
        val body: String?,
        val registrationYear: Int?,
        val bodyModifications: Boolean,
        val otherModiciations: Boolean,
        val vehicleFinanceType: String?,
        val additionalExcessCode: String?,
        val choiceOfRepairer: Boolean?,
        val commencementDate: String?,
        val coverType: String?,
        val hireCarOption: Boolean?,
        val instalmentPlanNumber: String?,
        val noClaimsDiscount: String?,
        val roadsideOption: Boolean?,
        val stampDutyExemption: String?,
        val windscreenOption: Boolean?,
        val ncdProtection: Boolean?,
        val insuranceProductProductCode: String?,
        val insuranceProductProductGroup: String?,
        var pricingMonthlyCanBuyOnline: Boolean? = false,
        var pricingMonthlyTotalPremium: String? = "",
        var pricingMonthlyUnderwritingResults: String? = "",
        var pricingYearlyCanBuyOnline: Boolean? = false,
        var pricingYearlyTotalPremium: String? = "",
        var pricingYearlyUnderwritingResults: String? = "",
        var knockout: Boolean = false,
        var applicationStatus: String = "",
        val applicationStartDate: String?,
        val applicationLastModifiedDate: String?,
        var totalNoOfHouseHoldDrivers: Int? = 0,
        var totalDrivers: Int? = 0,
        val paymentType: String?,
        var hasReachedQuoteStage: Boolean = false,
        var hasEmailedQuote: Boolean = false,
        var hasProgressedPastQuoteStage: Boolean = false,
        var hasReachedSaleStage: Boolean = false
) {}




